name: Github Pages with MKDocs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "https://github.com/BhavyaSree/PythonClass.git"
          ref: "main"
          token: ${{ github.token }}
          path: "sub/PythonClass"
          fetch-depth: "1"
      - run: |
          ln -s sub/PythonClass docs/Python
          tree
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force